# Generated by Django 3.2.9 on 2022-01-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200108_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishPremierLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamicon', models.ImageField(blank=True, null=True, upload_to='images/club')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='clubimage',
            field=models.ImageField(choices=[('Manchester', 'Manchester'), ('Arsenal', 'Arsenal'), ('Liverpool', 'Liverpool'), ('Chelsea', 'Chelsea'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Manchester', max_length=220, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
