# Generated by Django 3.2.9 on 2022-01-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220103_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.championleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Team1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.englishpremierleague'),
        ),
    ]
