# Generated by Django 3.2.9 on 2022-01-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220107_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bundeslga',
            new_name='Bundesliga',
        ),
    ]
