# Generated by Django 3.2.9 on 2022-01-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_bundeslga_bundesliga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Team1',
            new_name='EnglishPremierLeague',
        ),
        migrations.AddField(
            model_name='profile',
            name='Afcon',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.afconleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Baseball',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.baseball'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Bundesliga',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.bundesliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Europa',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.europaleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Formula1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.formula1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Laliga',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.laliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NBA',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.nba'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NFL',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.nfl'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Worldcup',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.worldcup'),
        ),
    ]
