# Generated by Django 3.2.9 on 2021-12-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
